-- DDL generated by Postico 1.5.10
-- Not all database features are supported. Do not use for backup.

-- Table Definition ----------------------------------------------

CREATE TABLE announcements (
    discussion_id integer,
    topic_id integer,
    CONSTRAINT announcements_pkey PRIMARY KEY (discussion_id, topic_id)
);



-- DDL generated by Postico 1.5.10
-- Not all database features are supported. Do not use for backup.

-- Table Definition ----------------------------------------------

CREATE TABLE banned_ip_addresses (
    id SERIAL PRIMARY KEY,
    ip cidr NOT NULL,
    admin_user_id integer NOT NULL,
    time timestamp without time zone NOT NULL
);

-- Indices -------------------------------------------------------

CREATE INDEX banned_ip_addresses_ip_idx ON banned_ip_addresses(ip inet_ops);
CREATE INDEX banned_ip_addresses_time_idx ON banned_ip_addresses(time timestamp_ops);



-- DDL generated by Postico 1.5.10
-- Not all database features are supported. Do not use for backup.

-- Table Definition ----------------------------------------------

CREATE TABLE bookmarks (
    user_id integer,
    post_id integer,
    notes text,
    CONSTRAINT bookmarks_pkey PRIMARY KEY (user_id, post_id)
);



-- DDL generated by Postico 1.5.10
-- Not all database features are supported. Do not use for backup.

-- Table Definition ----------------------------------------------

CREATE TABLE categories (
    id SERIAL PRIMARY KEY,
    title text NOT NULL,
    url text NOT NULL,
    description text,
    meta_description text,
    keywords text,
    sort smallint NOT NULL UNIQUE,
    created timestamp without time zone NOT NULL,
    hidden boolean NOT NULL,
    system boolean NOT NULL,
    locked boolean NOT NULL
);

-- Indices -------------------------------------------------------

CREATE INDEX categories_sort_idx ON categories(sort int2_ops);



-- DDL generated by Postico 1.5.10
-- Not all database features are supported. Do not use for backup.

-- Table Definition ----------------------------------------------

CREATE TABLE content (
    id SERIAL PRIMARY KEY,
    title_markdown text,
    title_html text,
    url text UNIQUE,
    content_markdown text,
    content_html text,
    author_id integer,
    created timestamp without time zone,
    modified timestamp without time zone,
    modified_by_id integer
);

-- Indices -------------------------------------------------------

CREATE INDEX author_id ON content(author_id int4_ops);
CREATE INDEX url ON content(url text_ops);



-- DDL generated by Postico 1.5.10
-- Not all database features are supported. Do not use for backup.

-- Table Definition ----------------------------------------------

CREATE TABLE discussion_permissions (
    group_id integer,
    discussion_id integer,
    read boolean NOT NULL,
    post boolean NOT NULL,
    reply boolean NOT NULL,
    CONSTRAINT discussion_permissions_pkey PRIMARY KEY (group_id, discussion_id)
);

-- Indices -------------------------------------------------------

CREATE INDEX discussion_permissions_discussionID_idx ON discussion_permissions(discussion_id int4_ops);
CREATE INDEX discussion_permissions_groupID_idx ON discussion_permissions(group_id int4_ops);
CREATE INDEX discussion_permissions_post_idx ON discussion_permissions(post bool_ops);
CREATE INDEX discussion_permissions_read_idx ON discussion_permissions(read bool_ops);
CREATE INDEX discussion_permissions_reply_idx ON discussion_permissions(reply bool_ops);



-- DDL generated by Postico 1.5.10
-- Not all database features are supported. Do not use for backup.

-- Table Definition ----------------------------------------------

CREATE TABLE discussions (
    id SERIAL PRIMARY KEY,
    category_id integer NOT NULL,
    title text NOT NULL,
    url text NOT NULL,
    description text,
    meta_description text,
    keywords text,
    posts integer NOT NULL,
    topics integer NOT NULL,
    sort smallint NOT NULL,
    created timestamp without time zone NOT NULL,
    hidden boolean NOT NULL,
    system boolean NOT NULL,
    locked boolean NOT NULL,
    last_post_id integer
);

-- Indices -------------------------------------------------------

CREATE INDEX discussions_category_id_idx ON discussions(category_id int4_ops);
CREATE INDEX discussions_sort_idx ON discussions(sort int2_ops);



-- DDL generated by Postico 1.5.10
-- Not all database features are supported. Do not use for backup.

-- Table Definition ----------------------------------------------

CREATE TABLE discussion_views (
    user_id integer,
    discussion_id integer,
    discussion_read timestamp without time zone NOT NULL,
    topics_read timestamp without time zone,
    CONSTRAINT discussion_views_pkey PRIMARY KEY (user_id, discussion_id)
);



-- DDL generated by Postico 1.5.10
-- Not all database features are supported. Do not use for backup.

-- Table Definition ----------------------------------------------

CREATE TABLE email_templates (
    name text PRIMARY KEY,
    description text,
    default_subject text NOT NULL,
    default_text text NOT NULL,
    subject text NOT NULL,
    text text NOT NULL,
    html text
);



-- DDL generated by Postico 1.5.10
-- Not all database features are supported. Do not use for backup.

-- Table Definition ----------------------------------------------

CREATE TABLE groups (
    id SERIAL PRIMARY KEY,
    name text NOT NULL UNIQUE,
    description text NOT NULL,
    login boolean NOT NULL,
    post boolean NOT NULL,
    reply boolean NOT NULL,
    talk_privately boolean NOT NULL,
    moderate_discussions boolean NOT NULL,
    administrate_discussions boolean NOT NULL,
    moderate_users boolean NOT NULL,
    administrate_users boolean NOT NULL,
    administrate_app boolean NOT NULL,
    bypass_lockdown boolean NOT NULL,
    system boolean NOT NULL,
    locked boolean NOT NULL,
    url text NOT NULL
);



-- DDL generated by Postico 1.5.10
-- Not all database features are supported. Do not use for backup.

-- Table Definition ----------------------------------------------

CREATE TABLE ignored_users (
    user_id integer,
    ignored_user_id integer,
    CONSTRAINT ignored_users_pkey PRIMARY KEY (user_id, ignored_user_id)
);



-- DDL generated by Postico 1.5.10
-- Not all database features are supported. Do not use for backup.

-- Table Definition ----------------------------------------------

CREATE TABLE moderators (
    user_id integer,
    discussion_id integer,
    CONSTRAINT moderators_pkey PRIMARY KEY (user_id, discussion_id)
);



-- DDL generated by Postico 1.5.10
-- Not all database features are supported. Do not use for backup.

-- Table Definition ----------------------------------------------

CREATE TABLE password_reset (
    user_id integer,
    verification_code text,
    time timestamp without time zone NOT NULL,
    CONSTRAINT password_reset_pkey PRIMARY KEY (user_id, verification_code)
);

-- Indices -------------------------------------------------------

CREATE INDEX password_reset_userID_idx ON password_reset(user_id int4_ops);
CREATE INDEX password_reset_verification_code_idx ON password_reset(verification_code text_ops);



-- DDL generated by Postico 1.5.10
-- Not all database features are supported. Do not use for backup.

-- Table Definition ----------------------------------------------

CREATE TABLE post_history (
    id serial PRIMARY KEY,
    post_id integer NOT NULL,
    editor_id integer,
    edit_reason text,
    text text NOT NULL,
    html text NOT NULL,
    time timestamp without time zone NOT NULL
);



-- DDL generated by Postico 1.5.10
-- Not all database features are supported. Do not use for backup.

-- Table Definition ----------------------------------------------

CREATE TABLE post_reports (
    id serial PRIMARY KEY,
    post_id integer NOT NULL,
    reported_by_id integer NOT NULL,
    reason text NOT NULL
);

-- Indices -------------------------------------------------------

CREATE INDEX post_reports_postID_idx ON post_reports(post_id int4_ops);
CREATE INDEX post_reports_reportedByID_idx ON post_reports(reported_by_id int4_ops);



-- DDL generated by Postico 1.5.10
-- Not all database features are supported. Do not use for backup.

-- Table Definition ----------------------------------------------

CREATE TABLE posts (
    id SERIAL PRIMARY KEY,
    topic_id integer NOT NULL,
    user_id integer NOT NULL,
    text text NOT NULL,
    html text NOT NULL,
    created timestamp without time zone NOT NULL,
    modified timestamp without time zone,
    draft boolean NOT NULL,
    editor_id integer,
    edit_reason text,
    locked_by_id integer,
    lock_reason text
);

-- Indices -------------------------------------------------------

CREATE INDEX posts_created_desc ON posts(created timestamp_ops DESC);
CREATE INDEX posts_created_idx ON posts(created timestamp_ops);
CREATE INDEX posts_draft_idx ON posts(draft bool_ops) WHERE draft = false;
CREATE INDEX posts_draft_idx1 ON posts(draft bool_ops);
CREATE INDEX posts_topic_id_created_idx ON posts(topic_id int4_ops,created timestamp_ops);
CREATE INDEX posts_topic_id_created_idx1 ON posts(topic_id int4_ops,created timestamp_ops DESC);
CREATE INDEX posts_topic_id_idx ON posts(topic_id int4_ops);
CREATE INDEX posts_topic_id_idx3 ON posts(topic_id int4_ops DESC);
CREATE INDEX posts_user_id_idx ON posts(user_id int4_ops);
CREATE INDEX posts_topic_id_draft_created ON posts(topic_id int4_ops,draft bool_ops,created timestamp_ops);



-- DDL generated by Postico 1.5.10
-- Not all database features are supported. Do not use for backup.

-- Table Definition ----------------------------------------------

CREATE TABLE post_trash (
    id integer PRIMARY KEY,
    topic_id integer NOT NULL,
    user_id integer NOT NULL,
    text text NOT NULL,
    html text NOT NULL,
    created timestamp without time zone NOT NULL,
    modified timestamp without time zone,
    draft boolean NOT NULL,
    editor_id integer,
    edit_reason text,
    locked_by_id integer,
    lock_reason text,
    deleted_by_id integer NOT NULL,
    delete_reason text
);



-- DDL generated by Postico 1.5.10
-- Not all database features are supported. Do not use for backup.

-- Table Definition ----------------------------------------------

CREATE TABLE topic_invitations (
    user_id integer,
    topic_id integer,
    accepted boolean DEFAULT false,
    left_topic boolean DEFAULT false,
    CONSTRAINT topic_invitations_pkey PRIMARY KEY (user_id, topic_id)
);

-- Indices -------------------------------------------------------

CREATE INDEX topic_invitations_topic_id_idx ON topic_invitations(topic_id int4_ops);
CREATE INDEX topic_invitations_topic_id_idx1 ON topic_invitations(topic_id int4_ops);
CREATE INDEX topic_invitations_user_id_idx ON topic_invitations(user_id int4_ops);
CREATE INDEX topic_invitations_user_id_idx1 ON topic_invitations(user_id int4_ops);
CREATE INDEX topic_invitations_accepted_idx ON topic_invitations(accepted bool_ops);
CREATE INDEX topic_invitations_left_idx ON topic_invitations(left_topic bool_ops);



-- DDL generated by Postico 1.5.10
-- Not all database features are supported. Do not use for backup.

-- Table Definition ----------------------------------------------

CREATE TABLE topics (
    id SERIAL PRIMARY KEY,
    discussion_id integer NOT NULL,
    title text NOT NULL,
    title_html text NOT NULL,
    url text NOT NULL,
    created timestamp without time zone NOT NULL,
    modified timestamp without time zone,
    sticky timestamp without time zone,
    replies integer DEFAULT 0,
    draft boolean NOT NULL,
    private boolean NOT NULL,
    locked_by_id integer,
    lock_reason text,
    edited_by_id integer,
    edit_reason text
);

-- Indices -------------------------------------------------------

CREATE INDEX topics_created_idx ON topics(created timestamp_ops);
CREATE INDEX topics_discussion_id_idx ON topics(discussion_id int4_ops);
CREATE INDEX topics_draft_idx ON topics(draft bool_ops);
CREATE INDEX topics_private_idx ON topics(private bool_ops);
CREATE INDEX topics_sticky_idx ON topics(sticky timestamp_ops);



-- DDL generated by Postico 1.5.10
-- Not all database features are supported. Do not use for backup.

-- Table Definition ----------------------------------------------

CREATE TABLE topic_subscriptions (
    user_id integer,
    topic_id integer,
    notification_sent timestamp without time zone NOT NULL,
    CONSTRAINT topic_subscriptions_pkey PRIMARY KEY (user_id, topic_id)
);

-- Indices -------------------------------------------------------

CREATE INDEX topic_subscriptions_notificationSent_idx ON topic_subscriptions(notification_sent timestamp_ops);
CREATE INDEX topic_subscriptions_topic_id_idx ON topic_subscriptions(topic_id int4_ops);
CREATE INDEX topic_subscriptions_user_id_idx ON topic_subscriptions(user_id int4_ops);



-- DDL generated by Postico 1.5.10
-- Not all database features are supported. Do not use for backup.

-- Table Definition ----------------------------------------------

CREATE TABLE topic_views (
    user_id integer,
    topic_id integer,
    time timestamp without time zone NOT NULL,
    CONSTRAINT topic_views_pkey PRIMARY KEY (user_id, topic_id)
);

-- Indices -------------------------------------------------------

CREATE INDEX topic_views_time_idx ON topic_views(time timestamp_ops);
CREATE INDEX topic_views_topic_id_idx ON topic_views(topic_id int4_ops);
CREATE INDEX topic_views_user_id_idx ON topic_views(user_id int4_ops);



-- DDL generated by Postico 1.5.10
-- Not all database features are supported. Do not use for backup.

-- Table Definition ----------------------------------------------

CREATE TABLE user_logs (
    id serial PRIMARY KEY,
    user_id integer NOT NULL,
    action text NOT NULL,
    ip cidr NOT NULL,
    time timestamp without time zone NOT NULL
);



-- DDL generated by Postico 1.5.10
-- Not all database features are supported. Do not use for backup.

-- Table Definition ----------------------------------------------

CREATE TABLE users (
    id SERIAL PRIMARY KEY,
    group_id integer NOT NULL,
    username text NOT NULL UNIQUE,
    username_hash text NOT NULL,
    password_hash text NOT NULL,
    url text NOT NULL,
    email text NOT NULL UNIQUE,
    timezone text NOT NULL,
    date_format text NOT NULL,
    theme text NOT NULL,
    signature text,
    signature_html text,
    last_activity timestamp without time zone NOT NULL,
    joined timestamp without time zone NOT NULL,
    website text,
    private_topic_email_notification boolean NOT NULL,
    subscription_email_notification boolean NOT NULL,
    activated boolean NOT NULL,
    activation_code text NOT NULL,
    system boolean NOT NULL,
    locked boolean NOT NULL
);
