ALTER TABLE public.announcements RENAME COLUMN "discussionID" TO discussion_id;
ALTER TABLE public.announcements RENAME COLUMN "topicID" TO topic_id;
ALTER TABLE public.bookmarks RENAME COLUMN "userID" TO user_id;
ALTER TABLE public.bookmarks RENAME COLUMN "postID" TO post_id;
ALTER TABLE public.categories RENAME COLUMN "metaDescription" TO meta_description;
ALTER TABLE public."discussionPermissions" RENAME TO discussion_permissions;
ALTER TABLE public.discussion_permissions RENAME COLUMN "groupID" TO group_id;
ALTER TABLE public.discussion_permissions RENAME COLUMN "discussionID" TO discussion_id;
ALTER TABLE public."discussionViews" RENAME TO discussion_views;
ALTER TABLE public.discussion_views RENAME COLUMN "userID" TO user_id;
ALTER TABLE public.discussion_views RENAME COLUMN "discussionID" TO discussion_id;
ALTER TABLE public.discussion_views RENAME COLUMN "discussionRead" TO discussion_read;
ALTER TABLE public.discussion_views RENAME COLUMN "topicsRead" TO topics_read;
ALTER TABLE public.discussions RENAME COLUMN "categoryID" TO category_id;
ALTER TABLE public.discussions RENAME COLUMN "metaDescription" TO meta_description;
ALTER TABLE public."emailTemplates" RENAME TO email_templates;
ALTER TABLE public."groups" RENAME COLUMN "talkPrivately" TO talk_privately;
ALTER TABLE public."groups" RENAME COLUMN "moderateDiscussions" TO moderate_discussions;
ALTER TABLE public."groups" RENAME COLUMN "administrateDiscussions" TO administrate_discussions;
ALTER TABLE public."groups" RENAME COLUMN "moderateUsers" TO moderate_users;
ALTER TABLE public."groups" RENAME COLUMN "administrateUsers" TO administrate_users;
ALTER TABLE public."groups" RENAME COLUMN "administrateApp" TO administrate_app;
ALTER TABLE public."groups" RENAME COLUMN "bypassLockdown" TO bypass_lockdown;
ALTER TABLE public."ignoredUsers" RENAME TO ignored_users;
ALTER TABLE public.ignored_users RENAME COLUMN "userID" TO user_id;
ALTER TABLE public.ignored_users RENAME COLUMN "ignoredUserID" TO ignored_user_id;
ALTER TABLE public.moderators RENAME COLUMN "userID" TO user_id;
ALTER TABLE public.moderators RENAME COLUMN "discussionID" TO discussion_id;
ALTER TABLE public."passwordReset" RENAME TO password_reset;
ALTER TABLE public.password_reset RENAME COLUMN "userID" TO user_id;
ALTER TABLE public.password_reset RENAME COLUMN "verificationCode" TO verification_code;
ALTER TABLE public."postHistory" RENAME TO post_history;
ALTER TABLE public.post_history RENAME COLUMN "postID" TO post_id;
ALTER TABLE public.post_history RENAME COLUMN "editorID" TO editor_id;
ALTER TABLE public.post_history RENAME COLUMN "editReason" TO edit_reason;
ALTER TABLE public."postReports" RENAME TO post_reports;
ALTER TABLE public.post_reports RENAME COLUMN "postID" TO post_id;
ALTER TABLE public.post_reports RENAME COLUMN "reportedByID" TO reported_by_id;
ALTER TABLE public."postTrash" RENAME TO post_trash;
ALTER TABLE public.post_trash RENAME COLUMN "topicID" TO topic_id;
ALTER TABLE public.post_trash RENAME COLUMN "userID" TO user_id;
ALTER TABLE public.post_trash RENAME COLUMN "editorID" TO editor_id;
ALTER TABLE public.post_trash RENAME COLUMN "editReason" TO edit_reason;
ALTER TABLE public.post_trash RENAME COLUMN "lockedByID" TO locked_by_id;
ALTER TABLE public.post_trash RENAME COLUMN "lockReason" TO lock_reason;
ALTER TABLE public.post_trash RENAME COLUMN "deletedByID" TO deleted_by_id;
ALTER TABLE public.post_trash RENAME COLUMN "deleteReason" TO delete_reason;
ALTER TABLE public.posts RENAME COLUMN "topicID" TO topic_id;
ALTER TABLE public.posts RENAME COLUMN "userID" TO user_id;
ALTER TABLE public.posts RENAME COLUMN "editorID" TO editor_id;
ALTER TABLE public.posts RENAME COLUMN "editReason" TO edit_reason;
ALTER TABLE public.posts RENAME COLUMN "lockedByID" TO locked_by_id;
ALTER TABLE public.posts RENAME COLUMN "lockReason" TO lock_reason;
ALTER TABLE public."topicInvitations" RENAME TO topic_invitations;
ALTER TABLE public.topic_invitations RENAME COLUMN "userID" TO user_id;
ALTER TABLE public.topic_invitations RENAME COLUMN "topicID" TO topic_id;
ALTER TABLE public.topic_invitations RENAME COLUMN "left" TO left_topic;
ALTER TABLE public."topicSubscriptions" RENAME TO topic_subscriptions;
ALTER TABLE public.topic_subscriptions RENAME COLUMN "userID" TO user_id;
ALTER TABLE public.topic_subscriptions RENAME COLUMN "topicID" TO topic_id;
ALTER TABLE public.topic_subscriptions RENAME COLUMN "notificationSent" TO notification_sent;
ALTER TABLE public."topicViews" RENAME TO topic_views;
ALTER TABLE public.topic_views RENAME COLUMN "userID" TO user_id;
ALTER TABLE public.topic_views RENAME COLUMN "topicID" TO topic_id;
ALTER TABLE public.topics RENAME COLUMN "discussionID" TO discussion_id;
ALTER TABLE public.topics RENAME COLUMN "titleHtml" TO title_html;
ALTER TABLE public.topics RENAME COLUMN "lockedByID" TO locked_by_id;
ALTER TABLE public.topics RENAME COLUMN "lockReason" TO lock_reason;
ALTER TABLE public.topics RENAME COLUMN "editedByID" TO edited_by_id;
ALTER TABLE public.topics RENAME COLUMN "editReason" TO edit_reason;
ALTER TABLE public."userLogs" RENAME TO user_logs;
ALTER TABLE public.user_logs RENAME COLUMN "userID" TO user_id;
ALTER TABLE public.users RENAME COLUMN "groupID" TO group_id;
ALTER TABLE public.users RENAME COLUMN "usernameHash" TO username_hash;
ALTER TABLE public.users RENAME COLUMN "passwordHash" TO password_hash;
ALTER TABLE public.users RENAME COLUMN "dateFormat" TO date_format;
ALTER TABLE public.users RENAME COLUMN "signatureHtml" TO signature_html;
ALTER TABLE public.users RENAME COLUMN "lastActivity" TO last_activity;
ALTER TABLE public.users RENAME COLUMN "privateTopicEmailNotification" TO private_topic_email_notification;
ALTER TABLE public.users RENAME COLUMN "subscriptionEmailNotification" TO subscription_email_notification;
ALTER TABLE public.users RENAME COLUMN "activationCode" TO activation_code;
